package com.swcommodities.wsmill.hibernate.dto;
// Generated Feb 18, 2014 3:38:53 PM by Hibernate Tools 3.2.1.GA


import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AccessoryMaster generated by hbm2java
 */
@Entity
@Table(name="accessory_master"

)
public class AccessoryMaster  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String unit;
     private Byte status;
     private Set<Accessories> accessorieses = new HashSet<Accessories>(0);

    public AccessoryMaster() {
    }

    public AccessoryMaster(String name, String unit, Byte status, Set<Accessories> accessorieses) {
       this.name = name;
       this.unit = unit;
       this.status = status;
       this.accessorieses = accessorieses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="unit")
    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }
    
    @Column(name="status")
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="accessoryMaster")
    public Set<Accessories> getAccessorieses() {
        return this.accessorieses;
    }
    
    public void setAccessorieses(Set<Accessories> accessorieses) {
        this.accessorieses = accessorieses;
    }




}


