package com.swcommodities.wsmill.hibernate.dto;
// Generated Feb 18, 2014 3:38:53 PM by Hibernate Tools 3.2.1.GA


import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Accessories generated by hbm2java
 */
@Entity
@Table(name="accessories"

)
public class Accessories  implements java.io.Serializable {


     private Integer id;
     private AccessoryMaster accessoryMaster;
     private ShippingInstruction shippingInstruction;
     private CompanyMaster companyMaster;
     private Float quantity;

    public Accessories() {
    }

    public Accessories(AccessoryMaster accessoryMaster, ShippingInstruction shippingInstruction, CompanyMaster companyMaster, Float quantity) {
       this.accessoryMaster = accessoryMaster;
       this.shippingInstruction = shippingInstruction;
       this.companyMaster = companyMaster;
       this.quantity = quantity;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="accessory_id")
    public AccessoryMaster getAccessoryMaster() {
        return this.accessoryMaster;
    }
    
    public void setAccessoryMaster(AccessoryMaster accessoryMaster) {
        this.accessoryMaster = accessoryMaster;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="inst_id")
    public ShippingInstruction getShippingInstruction() {
        return this.shippingInstruction;
    }
    
    public void setShippingInstruction(ShippingInstruction shippingInstruction) {
        this.shippingInstruction = shippingInstruction;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="supplier_id")
    public CompanyMaster getCompanyMaster() {
        return this.companyMaster;
    }
    
    public void setCompanyMaster(CompanyMaster companyMaster) {
        this.companyMaster = companyMaster;
    }
    
    @Column(name="quantity", precision=12, scale=0)
    public Float getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Float quantity) {
        this.quantity = quantity;
    }




}


