package com.swcommodities.wsmill.hibernate.dto;
// Generated Feb 18, 2014 3:38:53 PM by Hibernate Tools 3.2.1.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CellType generated by hbm2java
 */
@Entity
@Table(name = "cell_type"
)
public class CellType implements java.io.Serializable {

    private Integer id;
    private String cellTypeName;
    private String displayName;
    private Set<WarehouseCell> warehouseCells = new HashSet<WarehouseCell>(0);

    public CellType() {
    }

    public CellType(String cellTypeName, String displayName, Set<WarehouseCell> warehouseCells) {
        this.cellTypeName = cellTypeName;
        this.displayName = displayName;
        this.warehouseCells = warehouseCells;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "cell_type_name")
    public String getCellTypeName() {
        return this.cellTypeName;
    }

    public void setCellTypeName(String cellTypeName) {
        this.cellTypeName = cellTypeName;
    }

    @Column(name = "display_name")
    public String getDisplayName() {
        return this.displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "cellType")
    public Set<WarehouseCell> getWarehouseCells() {
        return this.warehouseCells;
    }

    public void setWarehouseCells(Set<WarehouseCell> warehouseCells) {
        this.warehouseCells = warehouseCells;
    }

}
