package com.swcommodities.wsmill.hibernate.dto;
// Generated Feb 18, 2014 3:38:53 PM by Hibernate Tools 3.2.1.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name = "city"
)
public class City implements java.io.Serializable {

    private Integer id;
    private int countryId;
    private String name;
    private Boolean active;
    private Set<Warehouse> warehouses = new HashSet<Warehouse>(0);
    private Set<ShippingInstruction> shippingInstructions = new HashSet<ShippingInstruction>(0);

    public City() {
    }

    public City(int countryId) {
        this.countryId = countryId;
    }

    public City(int countryId, String name, Boolean active, Set<Warehouse> warehouses, Set<ShippingInstruction> shippingInstructions) {
        this.countryId = countryId;
        this.name = name;
        this.active = active;
        this.warehouses = warehouses;
        this.shippingInstructions = shippingInstructions;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "country_id", nullable = false)
    public int getCountryId() {
        return this.countryId;
    }

    public void setCountryId(int countryId) {
        this.countryId = countryId;
    }

    @Column(name = "name")
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "active")
    public Boolean getActive() {
        return this.active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "city")
    public Set<Warehouse> getWarehouses() {
        return this.warehouses;
    }

    public void setWarehouses(Set<Warehouse> warehouses) {
        this.warehouses = warehouses;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "city")
    public Set<ShippingInstruction> getShippingInstructions() {
        return this.shippingInstructions;
    }

    public void setShippingInstructions(Set<ShippingInstruction> shippingInstructions) {
        this.shippingInstructions = shippingInstructions;
    }

}
