package com.swcommodities.wsmill.hibernate.dto;
// Generated Feb 18, 2014 3:38:53 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ClientPackingPriceId generated by hbm2java
 */
@Embeddable
public class ClientPackingPriceId implements java.io.Serializable {

    private int clientId;
    private int packingId;

    public ClientPackingPriceId() {
    }

    public ClientPackingPriceId(int clientId, int packingId) {
        this.clientId = clientId;
        this.packingId = packingId;
    }

    @Column(name = "client_id", nullable = false)
    public int getClientId() {
        return this.clientId;
    }

    public void setClientId(int clientId) {
        this.clientId = clientId;
    }

    @Column(name = "packing_id", nullable = false)
    public int getPackingId() {
        return this.packingId;
    }

    public void setPackingId(int packingId) {
        this.packingId = packingId;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof ClientPackingPriceId)) {
            return false;
        }
        ClientPackingPriceId castOther = (ClientPackingPriceId) other;

        return (this.getClientId() == castOther.getClientId())
            && (this.getPackingId() == castOther.getPackingId());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getClientId();
        result = 37 * result + this.getPackingId();
        return result;
    }

}
