package com.swcommodities.wsmill.hibernate.dto;
// Generated Feb 18, 2014 3:38:53 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CompanyRoleId generated by hbm2java
 */
@Embeddable
public class CompanyRoleId implements java.io.Serializable {

    private int companyId;
    private int roleId;

    public CompanyRoleId() {
    }

    public CompanyRoleId(int companyId, int roleId) {
        this.companyId = companyId;
        this.roleId = roleId;
    }

    @Column(name = "company_id", nullable = false)
    public int getCompanyId() {
        return this.companyId;
    }

    public void setCompanyId(int companyId) {
        this.companyId = companyId;
    }

    @Column(name = "role_id", nullable = false)
    public int getRoleId() {
        return this.roleId;
    }

    public void setRoleId(int roleId) {
        this.roleId = roleId;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof CompanyRoleId)) {
            return false;
        }
        CompanyRoleId castOther = (CompanyRoleId) other;

        return (this.getCompanyId() == castOther.getCompanyId())
            && (this.getRoleId() == castOther.getRoleId());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getCompanyId();
        result = 37 * result + this.getRoleId();
        return result;
    }

}
