package com.swcommodities.wsmill.hibernate.dto;
// Generated Feb 18, 2014 3:38:53 PM by Hibernate Tools 3.2.1.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Country generated by hbm2java
 */
@Entity
@Table(name = "country"
)
public class Country implements java.io.Serializable {

    private Integer id;
    private String iso2;
    private String shortName;
    private String longName;
    private String iso3;
    private String numcode;
    private String unMember;
    private String callingCode;
    private String cctld;

    public Country() {
    }

    public Country(String shortName, String longName) {
        this.shortName = shortName;
        this.longName = longName;
    }

    public Country(String iso2, String shortName, String longName, String iso3, String numcode, String unMember, String callingCode, String cctld, Set<PortMaster> portMasters, Set<PortMaster> portMasters_1) {
        this.iso2 = iso2;
        this.shortName = shortName;
        this.longName = longName;
        this.iso3 = iso3;
        this.numcode = numcode;
        this.unMember = unMember;
        this.callingCode = callingCode;
        this.cctld = cctld;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "iso2", length = 2)
    public String getIso2() {
        return this.iso2;
    }

    public void setIso2(String iso2) {
        this.iso2 = iso2;
    }

    @Column(name = "short_name", nullable = false)
    public String getShortName() {
        return this.shortName;
    }

    public void setShortName(String shortName) {
        this.shortName = shortName;
    }

    @Column(name = "long_name", nullable = false)
    public String getLongName() {
        return this.longName;
    }

    public void setLongName(String longName) {
        this.longName = longName;
    }

    @Column(name = "iso3", length = 3)
    public String getIso3() {
        return this.iso3;
    }

    public void setIso3(String iso3) {
        this.iso3 = iso3;
    }

    @Column(name = "numcode")
    public String getNumcode() {
        return this.numcode;
    }

    public void setNumcode(String numcode) {
        this.numcode = numcode;
    }

    @Column(name = "un_member")
    public String getUnMember() {
        return this.unMember;
    }

    public void setUnMember(String unMember) {
        this.unMember = unMember;
    }

    @Column(name = "calling_code")
    public String getCallingCode() {
        return this.callingCode;
    }

    public void setCallingCode(String callingCode) {
        this.callingCode = callingCode;
    }

    @Column(name = "cctld")
    public String getCctld() {
        return this.cctld;
    }

    public void setCctld(String cctld) {
        this.cctld = cctld;
    }

}
