package com.swcommodities.wsmill.hibernate.dto;
// Generated Feb 18, 2014 3:38:53 PM by Hibernate Tools 3.2.1.GA

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * GradeMaster generated by hbm2java
 */
@Entity
@Table(name = "grade_master")
public class GradeMaster extends AbstractTimestampEntity implements java.io.Serializable {

    private Integer id;
    private int originId;
    private int qualityId;
    private String name;
    private String description;
    private String descriptionVn;
    private Float fobDifferential;
    private Character type;
    private Byte active;
    private String beanSize;
    private String qualityTerm;
    private String qualityTermVn;
    private String report;
    private String reportDescription;
    private String reportDescriptionVn;
    private QualityMaster qualityMaster;

    public GradeMaster() {
    }

    public GradeMaster(Integer id) {
        this.id = id;
    }

    public GradeMaster(int originId, int qualityId) {
        this.originId = originId;
        this.qualityId = qualityId;
    }
    
    public static GradeMaster fromIdAndName(int id, String name) {
        GradeMaster gradeMaster = new GradeMaster(id);
        gradeMaster.setName(name);
        return gradeMaster;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "origin_id", nullable = false)
    public int getOriginId() {
        return this.originId;
    }

    public void setOriginId(int originId) {
        this.originId = originId;
    }

    @Column(name = "quality_id", nullable = false)
    public int getQualityId() {
        return this.qualityId;
    }

    public void setQualityId(int qualityId) {
        this.qualityId = qualityId;
    }

    @Column(name = "name")
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "description", length = 65535)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "description_vn", length = 65535)
    public String getDescriptionVn() {
        return descriptionVn;
    }

    public void setDescriptionVn(String descriptionVn) {
        this.descriptionVn = descriptionVn;
    }

    @Column(name = "fob_differential", precision = 9)
    public Float getFobDifferential() {
        return this.fobDifferential;
    }

    public void setFobDifferential(Float fobDifferential) {
        this.fobDifferential = fobDifferential;
    }

    @Column(name = "type", length = 1)
    public Character getType() {
        return this.type;
    }

    public void setType(Character type) {
        this.type = type;
    }

    @Column(name = "active")
    public Byte getActive() {
        return this.active;
    }

    public void setActive(Byte active) {
        this.active = active;
    }

    @Column(name = "bean_size", length = 65535)
    public String getBeanSize() {
        return this.beanSize;
    }

    public void setBeanSize(String beanSize) {
        this.beanSize = beanSize;
    }

    @Column(name = "quality_term", length = 65535)
    public String getQualityTerm() {
        return this.qualityTerm;
    }

    public void setQualityTerm(String qualityTerm) {
        this.qualityTerm = qualityTerm;
    }

    @Column(name = "quality_term_vn", length = 65535)
    public String getQualityTermVn() {
        return this.qualityTermVn;
    }

    public void setQualityTermVn(String qualityTermVn) {
        this.qualityTermVn = qualityTermVn;
    }

    @Column(name = "report", length = 65535)
    public String getReport() {
        return this.report;
    }

    public void setReport(String report) {
        this.report = report;
    }

    @Column(name = "report_description", length = 65535)
    public String getReportDescription() {
        return this.reportDescription;
    }

    public void setReportDescription(String reportDescription) {
        this.reportDescription = reportDescription;
    }

    @Column(name = "report_description_vn", length = 65535)
    public String getReportDescriptionVn() {
        return this.reportDescriptionVn;
    }

    public void setReportDescriptionVn(String reportDescriptionVn) {
        this.reportDescriptionVn = reportDescriptionVn;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "quality_master")
    public QualityMaster getQualityMaster() {
        return qualityMaster;
    }

    public GradeMaster setQualityMaster(QualityMaster qualityMaster) {
        this.qualityMaster = qualityMaster;
        return this;
    }

}
