package com.swcommodities.wsmill.hibernate.dto;
// Generated Feb 18, 2014 3:38:53 PM by Hibernate Tools 3.2.1.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.beans.Transient;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import java.util.TreeSet;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;

/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name = "menu")
public class Menu implements java.io.Serializable {

    private Integer id;
    //parent
    private Menu menu;
    // page belong to menu
    private Page page;
    private String name;
    private boolean default_;
    private Byte order;
    private boolean showInMainMenu = false;
    //child
    private Set<Menu> menus = new TreeSet<>();
    private boolean selected = false;

    public Menu() {
    }

    public Menu(Integer id) {
        this.id = id;
    }

    public Menu(String name, boolean default_) {
        this.name = name;
        this.default_ = default_;
        this.id = null;
    }

    public Menu(Menu menu, Page page, String name, boolean default_, Byte order, Set<Menu> menus) {
        this.menu = menu;
        this.page = page;
        this.name = name;
        this.default_ = default_;
        this.order = order;
        this.menus = menus;
        this.id = null;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "parent_id")
    public Menu getMenu() {
        return this.menu;
    }

    public void setMenu(Menu menu) {
        this.menu = menu;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "url_id")
    public Page getPage() {
        return this.page;
    }

    public void setPage(Page page) {
        this.page = page;
    }

    @Column(name = "name", nullable = false, length = 125)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "is_default", nullable = false)
    public boolean isDefault_() {
        return this.default_;
    }

    public void setDefault_(boolean default_) {
        this.default_ = default_;
    }

    @Column(name = "_order")
    public Byte getOrder() {
        return this.order;
    }

    public void setOrder(Byte order) {
        this.order = order;
    }

    // children
    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "menu")
    @OrderBy("order")
    public Set<Menu> getMenus() {
        return this.menus;
    }

    public void setMenus(Set<Menu> menus) {
        this.menus = menus;
    }

    @Transient
    public boolean getSelected() {
        return selected;
    }

    public void setSelected(boolean selected) {
        this.selected = selected;
    }

    public boolean isShowInMainMenu() {
        return showInMainMenu;
    }

    public void setShowInMainMenu(boolean showInMainMenu) {
        this.showInMainMenu = showInMainMenu;
    }

    @Override
    public String toString() {
        return "[Menu id=" + id + "]";
    }

}
