package com.swcommodities.wsmill.hibernate.dto;
// Generated Feb 18, 2014 3:38:53 PM by Hibernate Tools 3.2.1.GA

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PackingMaster generated by hbm2java
 */
@Entity
@Table(name = "packing_master")
public class PackingMaster extends AbstractTimestampEntity implements java.io.Serializable {

	private Integer id;
	private String name;
	private Float weight;
	private Float kgPerBag;
	private Float bagsPerPallet;
	private String description;
	private Byte status;
	private String log;
	
	public PackingMaster() {
	}

	public PackingMaster(Integer id) {
		this.id = id;
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "weight", precision = 12, scale = 0)
	public Float getWeight() {
		return this.weight;
	}

	public void setWeight(Float weight) {
		this.weight = weight;
	}

	@Column(name = "kg_per_bag", precision = 12, scale = 0)
	public Float getKgPerBag() {
		return this.kgPerBag;
	}

	public void setKgPerBag(Float kgPerBag) {
		this.kgPerBag = kgPerBag;
	}

	@Column(name = "bags_per_pallet", precision = 12, scale = 0)
	public Float getBagsPerPallet() {
		return this.bagsPerPallet;
	}

	public void setBagsPerPallet(Float bagsPerPallet) {
		this.bagsPerPallet = bagsPerPallet;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@Column(name = "log", length = 65535)
	public String getLog() {
		return this.log;
	}

	public void setLog(String log) {
		this.log = log;
	}
    
}
