package com.swcommodities.wsmill.hibernate.dto;
// Generated Feb 18, 2014 3:38:53 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PriceList generated by hbm2java
 */
@Entity
@Table(name = "price_list"
)
public class PriceList implements java.io.Serializable {

    private int id;
    private CompanyMaster companyMaster;
    private Float storage;
    private Float import_;
    private Float cleanGrade;
    private Float colorSort;
    private Float polishing;
    private Float reWeighing;
    private Float reBag;
    private Float dry;

    public PriceList() {
    }

    public PriceList(int id) {
        this.id = id;
    }

    public PriceList(int id, CompanyMaster companyMaster, Float storage, Float import_, Float cleanGrade, Float colorSort, Float polishing, Float reWeighing, Float reBag, Float dry) {
        this.id = id;
        this.companyMaster = companyMaster;
        this.storage = storage;
        this.import_ = import_;
        this.cleanGrade = cleanGrade;
        this.colorSort = colorSort;
        this.polishing = polishing;
        this.reWeighing = reWeighing;
        this.reBag = reBag;
        this.dry = dry;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "client_id")
    public CompanyMaster getCompanyMaster() {
        return this.companyMaster;
    }

    public void setCompanyMaster(CompanyMaster companyMaster) {
        this.companyMaster = companyMaster;
    }

    @Column(name = "storage", precision = 9)
    public Float getStorage() {
        return this.storage;
    }

    public void setStorage(Float storage) {
        this.storage = storage;
    }

    @Column(name = "import", precision = 9)
    public Float getImport_() {
        return this.import_;
    }

    public void setImport_(Float import_) {
        this.import_ = import_;
    }

    @Column(name = "clean_grade", precision = 9)
    public Float getCleanGrade() {
        return this.cleanGrade;
    }

    public void setCleanGrade(Float cleanGrade) {
        this.cleanGrade = cleanGrade;
    }

    @Column(name = "color_sort", precision = 9)
    public Float getColorSort() {
        return this.colorSort;
    }

    public void setColorSort(Float colorSort) {
        this.colorSort = colorSort;
    }

    @Column(name = "polishing", precision = 9)
    public Float getPolishing() {
        return this.polishing;
    }

    public void setPolishing(Float polishing) {
        this.polishing = polishing;
    }

    @Column(name = "re_weighing", precision = 9)
    public Float getReWeighing() {
        return this.reWeighing;
    }

    public void setReWeighing(Float reWeighing) {
        this.reWeighing = reWeighing;
    }

    @Column(name = "re_bag", precision = 9)
    public Float getReBag() {
        return this.reBag;
    }

    public void setReBag(Float reBag) {
        this.reBag = reBag;
    }

    @Column(name = "dry", precision = 9)
    public Float getDry() {
        return this.dry;
    }

    public void setDry(Float dry) {
        this.dry = dry;
    }

}
