package com.swcommodities.wsmill.hibernate.dto;
// Generated Feb 18, 2014 3:38:53 PM by Hibernate Tools 3.2.1.GA

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * StockHistories generated by hbm2java
 */
@Entity
@Table(name = "stock_histories"
)
public class StockHistories implements java.io.Serializable {

    private Integer id;
    private String content;
    private Long dateCode;

    public StockHistories() {
    }

    public StockHistories(String content, Long dateCode) {
        this.content = content;
        this.dateCode = dateCode;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "content")
    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    @Column(name = "date_code")
    public Long getDateCode() {
        return this.dateCode;
    }

    public void setDateCode(Long dateCode) {
        this.dateCode = dateCode;
    }

}
