package com.swcommodities.wsmill.hibernate.dto;
// Generated Feb 18, 2014 3:38:53 PM by Hibernate Tools 3.2.1.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StockHistorical generated by hbm2java
 */
@Entity
@Table(name = "stock_historical"
)
public class StockHistorical implements java.io.Serializable {

    private Integer id;
    private int gradeId;
    private Integer clientId;
    private String allocationRef;
    private String wnRef;
    private Float tons;
    private Integer num;
    private Integer packingId;
    private Date inDate;
    private Integer mapId;
    private String area;
    private Float blacks;
    private Float brown;
    private Float fm;
    private Float broken;
    private Float moist;
    private Float ocrop;
    private Float moldy;
    private String cup;
    private Float asc20;
    private Float sc20;
    private Float sc19;
    private Float sc18;
    private Float sc17;
    private Float sc16;
    private Float sc15;
    private Float sc14;
    private Float sc13;
    private Float sc12;
    private Float bsc12;
    private String type;
    private Date createdDate;
    private Integer piId;
    private Integer wnaId;
    private Integer wnaStt;
    private String wnaType;

    public StockHistorical() {
    }

    public StockHistorical(int gradeId, String wnRef) {
        this.gradeId = gradeId;
        this.wnRef = wnRef;
    }

    public StockHistorical(int gradeId, Integer clientId, String allocationRef, String wnRef, Float tons, Integer num, Integer packingId, Date inDate, Integer mapId, String area, Float blacks, Float brown, Float fm, Float broken, Float moist, Float ocrop, Float moldy, String cup, Float asc20, Float sc20, Float sc19, Float sc18, Float sc17, Float sc16, Float sc15, Float sc14, Float sc13, Float sc12, Float bsc12, String type, Date createdDate, Integer piId, Integer wnaId, Integer wnaStt, String wnaType) {
        this.gradeId = gradeId;
        this.clientId = clientId;
        this.allocationRef = allocationRef;
        this.wnRef = wnRef;
        this.tons = tons;
        this.num = num;
        this.packingId = packingId;
        this.inDate = inDate;
        this.mapId = mapId;
        this.area = area;
        this.blacks = blacks;
        this.brown = brown;
        this.fm = fm;
        this.broken = broken;
        this.moist = moist;
        this.ocrop = ocrop;
        this.moldy = moldy;
        this.cup = cup;
        this.asc20 = asc20;
        this.sc20 = sc20;
        this.sc19 = sc19;
        this.sc18 = sc18;
        this.sc17 = sc17;
        this.sc16 = sc16;
        this.sc15 = sc15;
        this.sc14 = sc14;
        this.sc13 = sc13;
        this.sc12 = sc12;
        this.bsc12 = bsc12;
        this.type = type;
        this.createdDate = createdDate;
        this.piId = piId;
        this.wnaId = wnaId;
        this.wnaStt = wnaStt;
        this.wnaType = wnaType;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "grade_id", nullable = false)
    public int getGradeId() {
        return this.gradeId;
    }

    public void setGradeId(int gradeId) {
        this.gradeId = gradeId;
    }

    @Column(name = "client_id")
    public Integer getClientId() {
        return this.clientId;
    }

    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }

    @Column(name = "allocation_ref")
    public String getAllocationRef() {
        return this.allocationRef;
    }

    public void setAllocationRef(String allocationRef) {
        this.allocationRef = allocationRef;
    }

    @Column(name = "wn_ref", nullable = false)
    public String getWnRef() {
        return this.wnRef;
    }

    public void setWnRef(String wnRef) {
        this.wnRef = wnRef;
    }

    @Column(name = "tons", precision = 9, scale = 3)
    public Float getTons() {
        return this.tons;
    }

    public void setTons(Float tons) {
        this.tons = tons;
    }

    @Column(name = "num")
    public Integer getNum() {
        return this.num;
    }

    public void setNum(Integer num) {
        this.num = num;
    }

    @Column(name = "packing_id")
    public Integer getPackingId() {
        return this.packingId;
    }

    public void setPackingId(Integer packingId) {
        this.packingId = packingId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "in_date", length = 10)
    public Date getInDate() {
        return this.inDate;
    }

    public void setInDate(Date inDate) {
        this.inDate = inDate;
    }

    @Column(name = "map_id")
    public Integer getMapId() {
        return this.mapId;
    }

    public void setMapId(Integer mapId) {
        this.mapId = mapId;
    }

    @Column(name = "area")
    public String getArea() {
        return this.area;
    }

    public void setArea(String area) {
        this.area = area;
    }

    @Column(name = "blacks", precision = 12, scale = 0)
    public Float getBlacks() {
        return this.blacks;
    }

    public void setBlacks(Float blacks) {
        this.blacks = blacks;
    }

    @Column(name = "brown", precision = 12, scale = 0)
    public Float getBrown() {
        return this.brown;
    }

    public void setBrown(Float brown) {
        this.brown = brown;
    }

    @Column(name = "fm", precision = 12, scale = 0)
    public Float getFm() {
        return this.fm;
    }

    public void setFm(Float fm) {
        this.fm = fm;
    }

    @Column(name = "broken", precision = 12, scale = 0)
    public Float getBroken() {
        return this.broken;
    }

    public void setBroken(Float broken) {
        this.broken = broken;
    }

    @Column(name = "moist", precision = 12, scale = 0)
    public Float getMoist() {
        return this.moist;
    }

    public void setMoist(Float moist) {
        this.moist = moist;
    }

    @Column(name = "ocrop", precision = 12, scale = 0)
    public Float getOcrop() {
        return this.ocrop;
    }

    public void setOcrop(Float ocrop) {
        this.ocrop = ocrop;
    }

    @Column(name = "moldy", precision = 12, scale = 0)
    public Float getMoldy() {
        return this.moldy;
    }

    public void setMoldy(Float moldy) {
        this.moldy = moldy;
    }

    @Column(name = "cup")
    public String getCup() {
        return this.cup;
    }

    public void setCup(String cup) {
        this.cup = cup;
    }

    @Column(name = "asc20", precision = 12, scale = 0)
    public Float getAsc20() {
        return this.asc20;
    }

    public void setAsc20(Float asc20) {
        this.asc20 = asc20;
    }

    @Column(name = "sc20", precision = 12, scale = 0)
    public Float getSc20() {
        return this.sc20;
    }

    public void setSc20(Float sc20) {
        this.sc20 = sc20;
    }

    @Column(name = "sc19", precision = 12, scale = 0)
    public Float getSc19() {
        return this.sc19;
    }

    public void setSc19(Float sc19) {
        this.sc19 = sc19;
    }

    @Column(name = "sc18", precision = 12, scale = 0)
    public Float getSc18() {
        return this.sc18;
    }

    public void setSc18(Float sc18) {
        this.sc18 = sc18;
    }

    @Column(name = "sc17", precision = 12, scale = 0)
    public Float getSc17() {
        return this.sc17;
    }

    public void setSc17(Float sc17) {
        this.sc17 = sc17;
    }

    @Column(name = "sc16", precision = 12, scale = 0)
    public Float getSc16() {
        return this.sc16;
    }

    public void setSc16(Float sc16) {
        this.sc16 = sc16;
    }

    @Column(name = "sc15", precision = 12, scale = 0)
    public Float getSc15() {
        return this.sc15;
    }

    public void setSc15(Float sc15) {
        this.sc15 = sc15;
    }

    @Column(name = "sc14", precision = 12, scale = 0)
    public Float getSc14() {
        return this.sc14;
    }

    public void setSc14(Float sc14) {
        this.sc14 = sc14;
    }

    @Column(name = "sc13", precision = 12, scale = 0)
    public Float getSc13() {
        return this.sc13;
    }

    public void setSc13(Float sc13) {
        this.sc13 = sc13;
    }

    @Column(name = "sc12", precision = 12, scale = 0)
    public Float getSc12() {
        return this.sc12;
    }

    public void setSc12(Float sc12) {
        this.sc12 = sc12;
    }

    @Column(name = "bsc12", precision = 12, scale = 0)
    public Float getBsc12() {
        return this.bsc12;
    }

    public void setBsc12(Float bsc12) {
        this.bsc12 = bsc12;
    }

    @Column(name = "type")
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "created_date", length = 10)
    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    @Column(name = "pi_id")
    public Integer getPiId() {
        return this.piId;
    }

    public void setPiId(Integer piId) {
        this.piId = piId;
    }

    @Column(name = "wna_id")
    public Integer getWnaId() {
        return this.wnaId;
    }

    public void setWnaId(Integer wnaId) {
        this.wnaId = wnaId;
    }

    @Column(name = "wna_stt")
    public Integer getWnaStt() {
        return this.wnaStt;
    }

    public void setWnaStt(Integer wnaStt) {
        this.wnaStt = wnaStt;
    }

    @Column(name = "wna_type")
    public String getWnaType() {
        return this.wnaType;
    }

    public void setWnaType(String wnaType) {
        this.wnaType = wnaType;
    }

}
