package com.swcommodities.wsmill.hibernate.dto;
// Generated Feb 18, 2014 3:38:53 PM by Hibernate Tools 3.2.1.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * WarehouseMap generated by hbm2java
 */
@Entity
@Table(name = "warehouse_map"
)
public class WarehouseMap implements java.io.Serializable {

    private Integer id;
    private User user;
    private Warehouse warehouse;
    private String name;
    private Integer width;
    private Integer height;
    private String wallHorizontal;
    private String wallVertical;
    private Byte status;
    private String log;
    private Set<WarehouseCell> warehouseCells = new HashSet<WarehouseCell>(0);

    public WarehouseMap() {
    }

    public WarehouseMap(Integer id) {
        this.id = id;
    }

    public WarehouseMap(User user, Warehouse warehouse, String name, Integer width, Integer height, String wallHorizontal, String wallVertical, Byte status, String log, Set<WarehouseCell> warehouseCells) {
        this.user = user;
        this.warehouse = warehouse;
        this.name = name;
        this.width = width;
        this.height = height;
        this.wallHorizontal = wallHorizontal;
        this.wallVertical = wallVertical;
        this.status = status;
        this.log = log;
        this.warehouseCells = warehouseCells;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id")
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "warehouse_id")
    public Warehouse getWarehouse() {
        return this.warehouse;
    }

    public void setWarehouse(Warehouse warehouse) {
        this.warehouse = warehouse;
    }

    @Column(name = "name")
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "width")
    public Integer getWidth() {
        return this.width;
    }

    public void setWidth(Integer width) {
        this.width = width;
    }

    @Column(name = "height")
    public Integer getHeight() {
        return this.height;
    }

    public void setHeight(Integer height) {
        this.height = height;
    }

    @Column(name = "wall_horizontal")
    public String getWallHorizontal() {
        return this.wallHorizontal;
    }

    public void setWallHorizontal(String wallHorizontal) {
        this.wallHorizontal = wallHorizontal;
    }

    @Column(name = "wall_vertical")
    public String getWallVertical() {
        return this.wallVertical;
    }

    public void setWallVertical(String wallVertical) {
        this.wallVertical = wallVertical;
    }

    @Column(name = "status")
    public Byte getStatus() {
        return this.status;
    }

    public void setStatus(Byte status) {
        this.status = status;
    }

    @Column(name = "log", length = 65535)
    public String getLog() {
        return this.log;
    }

    public void setLog(String log) {
        this.log = log;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "warehouseMap")
    public Set<WarehouseCell> getWarehouseCells() {
        return this.warehouseCells;
    }

    public void setWarehouseCells(Set<WarehouseCell> warehouseCells) {
        this.warehouseCells = warehouseCells;
    }

}
