package com.swcommodities.wsmill.hibernate.dto;
// Generated Feb 18, 2014 3:38:53 PM by Hibernate Tools 3.2.1.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Warehouse generated by hbm2java
 */
@Entity
@Table(name = "warehouse"
)
public class Warehouse implements java.io.Serializable {

    private Integer id;
    private City city;
    private String name;
    private String nameVn;
    private String type;
    private String address1;
    private String address1Vn;
    private String address2;
    private String address2Vn;
    private Boolean active;
    private String description;
    private Set<WarehouseMap> warehouseMaps = new HashSet<WarehouseMap>(0);
    private Set<DeliveryInstruction> deliveryInstructions = new HashSet<DeliveryInstruction>(0);

    public Warehouse() {
    }

    public Warehouse(Integer id) {
        this.id = id;
    }

    public Warehouse(City city, String name, String nameVn, String type, String address1, String address1Vn,
        String address2, String address2Vn, Boolean active, String description, Set<WarehouseMap> warehouseMaps,
        Set<DeliveryInstruction> deliveryInstructions) {
        this.city = city;
        this.name = name;
        this.nameVn = nameVn;
        this.type = type;
        this.address1 = address1;
        this.address1Vn = address1Vn;
        this.address2 = address2;
        this.address2Vn = address2Vn;
        this.active = active;
        this.description = description;
        this.warehouseMaps = warehouseMaps;
        this.deliveryInstructions = deliveryInstructions;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "city_id")
    public City getCity() {
        return this.city;
    }

    public void setCity(City city) {
        this.city = city;
    }

    @Column(name = "name")
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "name_vn")
    public String getNameVn() {
        return this.nameVn;
    }

    public void setNameVn(String nameVn) {
        this.nameVn = nameVn;
    }

    @Column(name = "type")
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Column(name = "address1")
    public String getAddress1() {
        return this.address1;
    }

    public void setAddress1(String address1) {
        this.address1 = address1;
    }

    @Column(name = "address1_vn")
    public String getAddress1Vn() {
        return this.address1Vn;
    }

    public void setAddress1Vn(String address1Vn) {
        this.address1Vn = address1Vn;
    }

    @Column(name = "address2")
    public String getAddress2() {
        return this.address2;
    }

    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    @Column(name = "address2_vn")
    public String getAddress2Vn() {
        return this.address2Vn;
    }

    public void setAddress2Vn(String address2Vn) {
        this.address2Vn = address2Vn;
    }

    @Column(name = "active")
    public Boolean getActive() {
        return this.active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    @Column(name = "description", length = 65535)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "warehouse")
    public Set<WarehouseMap> getWarehouseMaps() {
        return this.warehouseMaps;
    }

    public void setWarehouseMaps(Set<WarehouseMap> warehouseMaps) {
        this.warehouseMaps = warehouseMaps;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "warehouse")
    public Set<DeliveryInstruction> getDeliveryInstructions() {
        return this.deliveryInstructions;
    }

    public void setDeliveryInstructions(Set<DeliveryInstruction> deliveryInstructions) {
        this.deliveryInstructions = deliveryInstructions;
    }

}
