package com.swcommodities.wsmill.hibernate.dto;
// Generated Feb 18, 2014 3:38:53 PM by Hibernate Tools 3.2.1.GA

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * WeightLoss generated by hbm2java
 */
@Entity
@Table(name = "weight_loss"
)
public class WeightLoss implements java.io.Serializable {

    private Integer id;
    private ProcessingInstruction processingInstruction;
    private String log;
    private Float weightLoss;

    public WeightLoss() {
    }

    public WeightLoss(ProcessingInstruction processingInstruction, String log, Float weightLoss) {
        this.processingInstruction = processingInstruction;
        this.log = log;
        this.weightLoss = weightLoss;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "pi_id")
    public ProcessingInstruction getProcessingInstruction() {
        return this.processingInstruction;
    }

    public void setProcessingInstruction(ProcessingInstruction processingInstruction) {
        this.processingInstruction = processingInstruction;
    }

    @Column(name = "log", length = 65535)
    public String getLog() {
        return this.log;
    }

    public void setLog(String log) {
        this.log = log;
    }

    @Column(name = "weight_loss", precision = 12, scale = 0)
    public Float getWeightLoss() {
        return this.weightLoss;
    }

    public void setWeightLoss(Float weightLoss) {
        this.weightLoss = weightLoss;
    }

}
