package com.swcommodities.wsmill.hibernate.dto;
// Generated Feb 18, 2014 3:38:53 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * WnrMovmentId generated by hbm2java
 */
@Embeddable
public class WnrMovmentId implements java.io.Serializable {

    private int wnrId;
    private int movementId;

    public WnrMovmentId() {
    }

    public WnrMovmentId(int wnrId, int movementId) {
        this.wnrId = wnrId;
        this.movementId = movementId;
    }

    @Column(name = "wnr_id", nullable = false)
    public int getWnrId() {
        return this.wnrId;
    }

    public void setWnrId(int wnrId) {
        this.wnrId = wnrId;
    }

    @Column(name = "movement_id", nullable = false)
    public int getMovementId() {
        return this.movementId;
    }

    public void setMovementId(int movementId) {
        this.movementId = movementId;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof WnrMovmentId)) {
            return false;
        }
        WnrMovmentId castOther = (WnrMovmentId) other;

        return (this.getWnrId() == castOther.getWnrId())
            && (this.getMovementId() == castOther.getMovementId());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getWnrId();
        result = 37 * result + this.getMovementId();
        return result;
    }

}
