package com.swcommodities.wsmill.hibernate.dto;
// Generated Feb 18, 2014 3:38:53 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * WnrMovment generated by hbm2java
 */
@Entity
@Table(name = "wnr_movment"
)
public class WnrMovment implements java.io.Serializable {

    private WnrMovmentId id;

    public WnrMovment() {
    }

    public WnrMovment(WnrMovmentId id) {
        this.id = id;
    }

    @EmbeddedId

    @AttributeOverrides({
        @AttributeOverride(name = "wnrId", column = @Column(name = "wnr_id", nullable = false))
        , 
        @AttributeOverride(name = "movementId", column = @Column(name = "movement_id", nullable = false))})
    public WnrMovmentId getId() {
        return this.id;
    }

    public void setId(WnrMovmentId id) {
        this.id = id;
    }

}
