package com.swcommodities.wsmill.hibernate.clientDto;
import java.util.Date;

import com.swcommodities.wsmill.utils.Constants;

/**
 * DeliveryInstruction generated by hbm2java
 */
public class DeliveryInstructionClone implements java.io.Serializable {

	private Integer id;
	private Integer user;
	private Integer companyMasterByClientId;
	private Integer companyMasterByWeightControllerId;
	private Integer companyMasterBySupplierId;
	private Integer companyMasterByControllerId;
	private Integer gradeMaster;
	private Integer packingMaster;
	private Integer companyMasterByPledger;
	private Integer warehouse;
	private Integer companyMasterByQualityControllerId;
	private String refNumber;
	private String clientRef;
	private Date date;
	private String supplierRef;
	private Double tons = Double.parseDouble("0");
	private Float kgPerBag;
	private Integer noOfBags;
	private Date deliveryDate;
	private String fromTime;
	private String toTime;
	private String markingOnBags;
	private Integer originId;
	private Integer qualityId;
	private String remark;
	private Byte status = Constants.PENDING;
	private String log;
	private String supllierRef;
	private Integer originMaster;
	private Integer location;
	private Integer locationMaster;
	private Integer qualificationCompany;
	private Date firstDate;
	private Date lastDate;
	private Integer userByRequestUserId;
	private Integer userByUpdateUserId;
	private Date updateDate;
	private Date requestDate;
	private Byte requestStatus;
	private Date userUpdateDate;
	private int deleteStatus = 2;
	private String requestRemark;
	private Integer qualityMaster;
	private Boolean isCompletable;
	private Double deliverd;
	private Double pending;

	public DeliveryInstructionClone() {
		
	}
	
	

}
