package com.swcommodities.wsmill.hibernate.dto.view;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PriceList generated by hbm2java
 */
@Entity
@Table(name = "price_list")
public class PriceListView implements java.io.Serializable {

	private Integer id;
	private Integer client;
	private Float storage;
	private Float imp;
	private Float cleanGrade;
	private Float colorSort;
	private Float polishing;
	private Float reWeighing;
	private Float rebag;
	private Float dry;
	private Float jumbo;
	private Float bigbag;
	private Float jute;
	private Float pp;
	private Float bulk;
	private String userName;
	private Date updatedDate;
	private String log;

	public PriceListView() {
	}

	public PriceListView(int id) {
		this.id = id;
	}

	public PriceListView(Integer id, Integer client, Float storage, Float imp,
			Float cleanGrade, Float colorSort, Float polishing, Float reWeighing, Float rebag,
			Float dry, Float jumbo, Float bigbag, Float jute, Float pp, Float bulk,
			String userName, Date updatedDate, String log) {
		super();
		this.id = id;
		this.client = client;
		this.storage = storage;
		this.imp = imp;
		this.cleanGrade = cleanGrade;
		this.colorSort = colorSort;
		this.polishing = polishing;
		this.reWeighing = reWeighing;
		this.rebag = rebag;
		this.dry = dry;
		this.jumbo = jumbo;
		this.bigbag = bigbag;
		this.jute = jute;
		this.pp = pp;
		this.bulk = bulk;
		this.userName = userName;
		this.updatedDate = updatedDate;
		this.log = log;
	}

	@Id @GeneratedValue(strategy=IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "client_id")
	public Integer getClient() {
		return this.client;
	}

	public void setClient(Integer client) {
		this.client = client;
	}

	@Column(name = "storage", precision = 9)
	public Float getStorage() {
		return this.storage;
	}

	public void setStorage(Float storage) {
		this.storage = storage;
	}

	@Column(name = "import", precision = 9)
	public Float getImp() {
		return this.imp;
	}

	public void setImp(Float imp) {
		this.imp = imp;
	}

	@Column(name = "clean_grade", precision = 9)
	public Float getCleanGrade() {
		return this.cleanGrade;
	}

	public void setCleanGrade(Float cleanGrade) {
		this.cleanGrade = cleanGrade;
	}

	@Column(name = "color_sort", precision = 9)
	public Float getColorSort() {
		return this.colorSort;
	}

	public void setColorSort(Float colorSort) {
		this.colorSort = colorSort;
	}

	@Column(name = "polishing", precision = 9)
	public Float getPolishing() {
		return this.polishing;
	}

	public void setPolishing(Float polishing) {
		this.polishing = polishing;
	}

	@Column(name = "re_weighing", precision = 9)
	public Float getReWeighing() {
		return this.reWeighing;
	}

	public void setReWeighing(Float reWeighing) {
		this.reWeighing = reWeighing;
	}

	@Column(name = "re_bag", precision = 9)
	public Float getRebag() {
		return this.rebag;
	}

	public void setRebag(Float reBag) {
		this.rebag = reBag;
	}

	@Column(name = "dry", precision = 9)
	public Float getDry() {
		return this.dry;
	}

	public void setDry(Float dry) {
		this.dry = dry;
	}

	@Column(name = "jumbo_bag", precision = 9)
	public Float getJumbo() {
		return jumbo;
	}

	public void setJumbo(Float jumbo) {
		this.jumbo = jumbo;
	}

	@Column(name = "big_bag", precision = 9)
	public Float getBigbag() {
		return bigbag;
	}

	public void setBigbag(Float bigbag) {
		this.bigbag = bigbag;
	}

	@Column(name = "jute_bag", precision = 9)
	public Float getJute() {
		return jute;
	}

	public void setJute(Float jute) {
		this.jute = jute;
	}

	@Column(name = "pp", precision = 9)
	public Float getPp() {
		return pp;
	}

	public void setPp(Float pp) {
		this.pp = pp;
	}
	@Column(name = "user_name")
	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "log", length = 65535)
	public String getLog() {
		return log;
	}

	public void setLog(String log) {
		this.log = log;
	}

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_date", length=19)
	public Date getUpdatedDate() {
		return updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name="bulk")
	public Float getBulk() {
		return bulk;
	}

	public void setBulk(Float bulk) {
		this.bulk = bulk;
	}

}
