package com.swcommodities.wsmill.hibernate.dto.view;
// Generated Aug 26, 2013 5:19:13 PM by Hibernate Tools 3.6.0


import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.swcommodities.wsmill.json.jackson.JsonDateSerializer;

/**
 * WeightNoteReceipt generated by hbm2java
 */
@Entity
@Table(name="weight_note_receipt"

)
public class WeightNoteReceiptView  implements java.io.Serializable {


     private Integer id;
     private Integer areaId;
     private Integer wnId;
     private Integer packingId;
     private String refNumber;
     private Date date;
     private Integer noOfBags;
     private Float grossWeight;
     private Float tareWeight;
     private String palletName;
     private Float palletWeight;
     private String log;
     private Byte status;
     private String options;
     private Integer gradeId;
     private Integer clientId;
     private Integer pledgeId;
     private String movementId;
     
    public WeightNoteReceiptView() {
    }

    public WeightNoteReceiptView(Integer id, Integer areaId, Integer wnId, Integer packingId, String refNumber, Date date, Integer noOfBags, Float grossWeight, Float tareWeight, String palletName, Float palletWeight, String log, Byte status, String options, Integer gradeId, Integer clientId, Integer pledgeId, String movementId) {
        this.id = id;
        this.areaId = areaId;
        this.wnId = wnId;
        this.packingId = packingId;
        this.refNumber = refNumber;
        this.date = date;
        this.noOfBags = noOfBags;
        this.grossWeight = grossWeight;
        this.tareWeight = tareWeight;
        this.palletName = palletName;
        this.palletWeight = palletWeight;
        this.log = log;
        this.status = status;
        this.options = options;
        this.gradeId = gradeId;
        this.clientId = clientId;
        this.pledgeId = pledgeId;
        this.movementId = movementId;
    }

     @Id @GeneratedValue(strategy=IDENTITY)
     @Column(name = "id")
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name = "area_id")
    public Integer getAreaId() {
        return areaId;
    }

    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    @Column(name = "wn_id")
    public Integer getWnId() {
        return wnId;
    }

    public void setWnId(Integer wnId) {
        this.wnId = wnId;
    }

    @Column(name = "packing_id")
    public Integer getPackingId() {
        return packingId;
    }

    public void setPackingId(Integer packingId) {
        this.packingId = packingId;
    }

    @Column(name = "ref_number")
    public String getRefNumber() {
        return refNumber;
    }

    public void setRefNumber(String refNumber) {
        this.refNumber = refNumber;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "date", length = 10)
    @JsonSerialize(using = JsonDateSerializer.class)
    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    @Column(name = "no_of_bags")
    public Integer getNoOfBags() {
        return noOfBags;
    }

    public void setNoOfBags(Integer noOfBags) {
        this.noOfBags = noOfBags;
    }

    @Column(name = "gross_weight")
    public Float getGrossWeight() {
        return grossWeight;
    }

    public void setGrossWeight(Float grossWeight) {
        this.grossWeight = grossWeight;
    }

    @Column(name = "tare_weight")
    public Float getTareWeight() {
        return tareWeight;
    }

    public void setTareWeight(Float tareWeight) {
        this.tareWeight = tareWeight;
    }

    @Column(name = "pallet_name")
    public String getPalletName() {
        return palletName;
    }

    public void setPalletName(String palletName) {
        this.palletName = palletName;
    }

    @Column(name = "pallet_weight", precision = 12, scale = 0)
    public Float getPalletWeight() {
        return palletWeight;
    }

    public void setPalletWeight(Float palletWeight) {
        this.palletWeight = palletWeight;
    }

    @Column(name = "log")
    public String getLog() {
        return log;
    }

    public void setLog(String log) {
        this.log = log;
    }

    @Column(name = "status")
    public Byte getStatus() {
        return status;
    }

    public void setStatus(Byte status) {
        this.status = status;
    }

    @Column(name = "options")
    public String getOptions() {
        return options;
    }

    public void setOptions(String options) {
        this.options = options;
    }

    @Column(name = "grade_id")
    public Integer getGradeId() {
        return gradeId;
    }

    public void setGradeId(Integer gradeId) {
        this.gradeId = gradeId;
    }

    @Column(name = "client_id")
    public Integer getClientId() {
        return clientId;
    }

    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }

    @Column(name = "pledge_id")
    public Integer getPledgeId() {
        return pledgeId;
    }

    public void setPledgeId(Integer pledgeId) {
        this.pledgeId = pledgeId;
    }

    @Column(name = "movement_id")
    public String getMovementId() {
        return movementId;
    }

    public void setMovementId(String movementId) {
        this.movementId = movementId;
    }

    
}